### PR TITLE
Simple fix for error

### PR DESCRIPTION
**Pull request by WEEZOOKARP**
When you have more vehicles for sale than there are spaces players get errors, tested this fix on my server and it works pretty well.
When all spaces are taken new vehicles will not be spawned until a space is opened

### CODE REVIEW

**Comment by MonkeyWhisper** [comment]
Testing on live server.

**Comment by vosscat** [comment]
error remain
client/man.lua:360: attempt to compare nil with number

**Comment by MonkeyWhisper** [comment]
Yup, that is correct. Error still remains there.

**Comment by WEEZOOKARP** [comment]
works for me so i don't know how exactly you are getting errors
especially since your errors are coming from completely separate lines from the error that caused me to create this pull

**Comment by MonkeyWhisper** [comment]
PR does not fix the error.

**Review by MonkeyWhisper — APPROVED** [review]
PR fixed error. Ensure you delete the server cache if you are implementing this new PR.

**Comment by vosscat** [comment]
image
It's the same line 360 error where you wanna list your car as used for sale. The other one on line 287 is when you wanna sale your car directly.

**Comment by MonkeyWhisper** [comment]
> image It's the same line 360 error where you wanna list your car as used for sale. The other one on line 287 is when you wanna sale your car directly.

Oh wait a minute. I was not getting that error. Can you try clearing your server cache, restart and let me know?

**Comment by WEEZOOKARP** [comment]
image
10 cars going into 9 slots gives this error
image
the pull request limits the number of vehicles spawned to a value set in the config file. this number should be the same as the number of spaces your vehicles can be parked in or lower if you want to for whatever reason

**Comment by WEEZOOKARP** [comment]
the error scrreenshot above is what i fixed not the error vosscat was getting

**Comment by vosscat** [comment]
> > image It's the same line 360 error where you wanna list your car as used for sale. The other one on line 287 is when you wanna sale your car directly.
> 
> Oh wait a minute. I was not getting that error. Can you try clearing your server cache, restart and let me know?

same error

**Comment by vosscat** [comment]
> the error scrreenshot above is what i fixed not the error vosscat was getting

i thought it because you mentioned the issue which is the same as mine

**Comment by WEEZOOKARP** [comment]
i looked at the error and it looked the same but I didn't notice the lines were different so just went for it

**Pull request closed without merging**
