### PR TITLE
Working and tested fix for selling vehicle back!

### PR DESCRIPTION
**Pull request by NoobySloth**
This is the only solution I could get working. If there's a better way to do it, go ahead but this is confirmed working.

See the video where I tested. I've got mine set to 0.75 to give 1/3 of the car's price back. 40000 * 0.75 = 30000
https://nooby.xyz/nooby/f/ZQCW8i-08-06-2022.mp4

### CODE REVIEW

**Comment by NoobySloth** [comment]
> 

Every time I would attempt to sell the vehicle back to the dealership I was presented with the below error

[script:qb-vehiclesal] SCRIPT ERROR: @qb-vehiclesales/server/main.lua:90: attempt to perform arithmetic on a nil value (local 'price')

**Comment by GhzGarage** [comment]
Hmm alright

**Comment by NoobySloth** [comment]
> Hmm alright

Yeah, was an odd one BUT good thing is, it works now😂

**Comment by FjamZoo** [comment]
Can you add a break after finding the price as we no longer want the loop to continue after we have found a match thanks.

**Pull request merged**
